title: Aswini Abraham | Blog
description: > # this means to ignore newlines until "baseurl:"
  Projects on applications of statistics in everyday life.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Aswini Abraham # add your name
author-img: profilepic1.jpg # add your photo
about-author: I am a student of statistics trying to explore practical applications of statistics in everyday life # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: aswiniab # add your Github handle
social-linkedin: aswini-abraham-33196a85 # add your Linkedin handle
social-email: aswiniabraham@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
